# Google App Engine configuration (Alternative to Cloud Run)
runtime: nodejs18

# Use automatic scaling
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  NODE_ENV: 'production'
  PORT: '80'

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
