# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/budget-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/budget-api:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/budget-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/budget-api:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'budget-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/budget-api:$COMMIT_SHA'
      - '--region'
      - 'us-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--add-cloudsql-instances'
      - 'budget-project-483219:us-south1:budget-app'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=80,DB_NAME=postgres,DB_USER=postgres'
      - '--set-secrets'
      - 'DB_PASSWORD=budget-db-password:latest'

images:
  - 'gcr.io/$PROJECT_ID/budget-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/budget-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
